version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  profile:
    build:
      context: ./
      dockerfile: ./apps/user/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgresProfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev user

  user:
    build:
      context: ./
      dockerfile: ./apps/user/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgresUser
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev user

  microserviceApp:
    build:
      context: ./
      dockerfile: ./apps/microservice-app/Dockerfile
    ports:
      - '3000:5000'
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev microservice-app

  postgresUser:
    container_name: postgresUser
    image: postgres:latest
    environment:
      POSTGRES_DB: 'user'
      POSTGRES_PASSWORD: '2002rr'
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - dataUser:/var/lib/postgresql/data
    restart: always

  postgresProfile:
    container_name: postgresProfile
    image: postgres:latest
    environment:
      POSTGRES_DB: 'profile'
      POSTGRES_PASSWORD: '2002rr'
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - dataUser:/var/lib/postgresql/data
    restart: always
